inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"
require:
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3.6

RSpec/MultipleExpectations:
  Max: 3

RSpec/DescribedClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
