inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"
require:
  - rubocop-capybara
  - rubocop-rspec_rails
  - rubocop-factory_bot
plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.2

RSpec/MultipleExpectations:
  Max: 3

RSpec/DescribedClass:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'
